development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: sarahmelton
  password: Xairos1983!
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: sarahmelton
  password: Xairos1983!